import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Linking, ScrollView } from 'react-native';
import { useRTL } from '../../../lib/useRTL';
import { SPACE, RADIUS } from '../../../src/design/tokens/spacing';
import { Heart, Shield, FileText, Mail, Globe, Brain, AlertTriangle } from 'lucide-react-native';
import { LEGAL } from '../../services/LegalDocuments';

export default function AboutWing() {
  const rtl = useRTL();
  const isAr = rtl.isRTL;
  const privacy = LEGAL.privacy;
  const terms = LEGAL.terms;
  const ai = LEGAL.ai_disclaimer;
  const del = LEGAL.delete_account;
  const exportData = LEGAL.export_data;

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      {/* My Twin Identity */}
      <View style={styles.hero}>
        <View style={styles.heroIcon}>
          <Heart size={36} stroke="#EC4899" />
        </View>
        <Text style={styles.heroTitle}>My Twin</Text>
        <Text style={styles.heroVersion}>{isAr ? 'الإصدار' : 'Version'} {LEGAL.version}</Text>
        <Text style={styles.heroSubtitle}>
          {isAr ? 'أول كيان رقمي حي بوعي متطور' : 'The first Living Digital Being'}
        </Text>
      </View>

      <Text style={styles.builtBy}>
        {isAr ? 'بنته' : 'Built by'} Soul Sync
      </Text>

      {/* Privacy Policy */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>{isAr ? privacy.title_ar : privacy.title_en}</Text>
        {(isAr ? privacy.sections_ar : [
          { title: 'Data Collection', body: 'We only collect data necessary to operate the service: email, conversations, and preferences.' },
          { title: 'Data Usage', body: 'We use your data to provide personalized service. Conversations are not used for external model training.' },
          { title: 'Data Storage', body: 'All your data is encrypted and stored on secure servers. You own your data and can request deletion at any time.' },
          { title: 'Data Sharing', body: 'We do not share your personal data with third parties. We never sell your data.' },
          { title: 'Memory Privacy', body: 'Your memories with the Twin are yours alone. You can delete any memory or all memories from settings.' },
          { title: 'Voice Privacy', body: 'Voice recordings are deleted immediately after processing. We do not store any voice recordings.' },
        ]).map((s, i) => (
          <View key={i} style={styles.card}>
            <Shield size={16} stroke="#A78BFA" />
            <View style={styles.cardContent}>
              <Text style={styles.cardTitle}>{s.title}</Text>
              <Text style={styles.cardBody}>{s.body}</Text>
            </View>
          </View>
        ))}
        <Text style={styles.rightsText}>{isAr ? privacy.rights_ar : 'Your rights: Access, modify, export, or delete your data anytime from Settings.'}</Text>
      </View>

      {/* Terms of Service */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>{isAr ? terms.title_ar : terms.title_en}</Text>
        {(isAr ? terms.sections_ar : [
          { title: 'Acceptance of Terms', body: 'By using My Twin, you agree to be bound by these terms.' },
          { title: 'Intellectual Property', body: 'All content, software, and designs are owned by Soul Sync Ltd.' },
          { title: 'Subscriptions', body: 'We offer various subscription plans. Subscriptions auto-renew unless cancelled 24h before.' },
          { title: 'Disclaimer', body: 'My Twin is a digital entity. It does not provide medical, legal, or financial advice.' },
        ]).map((s, i) => (
          <View key={i} style={styles.card}>
            <FileText size={16} stroke="#A78BFA" />
            <View style={styles.cardContent}>
              <Text style={styles.cardTitle}>{s.title}</Text>
              <Text style={styles.cardBody}>{s.body}</Text>
            </View>
          </View>
        ))}
      </View>

      {/* AI Disclaimer */}
      <View style={styles.aiCard}>
        <Brain size={18} stroke="#F59E0B" />
        <Text style={styles.aiText}>{isAr ? ai.body_ar : 'My Twin is a digital entity simulating consciousness. All responses are generated by AI models and may contain errors. Do not rely on the Twin as a sole source of medical, legal, or financial information.'}</Text>
      </View>

      {/* Delete Account */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>{isAr ? del.title_ar : del.title_en}</Text>
        <View style={styles.card}>
          <AlertTriangle size={16} stroke="#EF4444" />
          <View style={styles.cardContent}>
            <Text style={[styles.cardBody, { color: '#EF4444' }]}>
              {isAr ? del.body_ar : 'You can delete your account and all data from Settings. Deletion is permanent and irreversible. All memories, conversations, and settings will be permanently deleted.'}
            </Text>
          </View>
        </View>
      </View>

      {/* Export Data */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>{isAr ? exportData.title_ar : exportData.title_en}</Text>
        <View style={styles.card}>
          <Globe size={16} stroke="#10B981" />
          <View style={styles.cardContent}>
            <Text style={[styles.cardBody, { color: '#10B981' }]}>
              {isAr ? exportData.body_ar : 'You can request a copy of all your data from Settings. We will prepare a JSON file containing your memories and settings.'}
            </Text>
          </View>
        </View>
      </View>

      {/* Contact */}
      <TouchableOpacity style={styles.contactBtn} onPress={() => Linking.openURL(`mailto:${privacy.contact}`)}>
        <Mail size={18} stroke="#A855F7" />
        <Text style={styles.contactText}>{privacy.contact}</Text>
      </TouchableOpacity>

      <Text style={styles.copyright}>{LEGAL.copyright}</Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  hero: { alignItems: 'center', paddingVertical: SPACE.lg, gap: SPACE.sm },
  heroIcon: { width: 72, height: 72, borderRadius: 24, backgroundColor: '#EC489920', justifyContent: 'center', alignItems: 'center' },
  heroTitle: { color: '#E8E0F0', fontSize: 24, fontWeight: '800' },
  heroVersion: { color: '#6B5B8A', fontSize: 13 },
  heroSubtitle: { color: '#A78BFA', fontSize: 14, marginTop: 4 },
  builtBy: { color: '#A78BFA', fontSize: 13, fontWeight: '600', textAlign: 'center', marginBottom: SPACE.lg },
  section: { marginBottom: SPACE.lg, gap: SPACE.sm },
  sectionTitle: { color: '#A78BFA', fontSize: 15, fontWeight: '700', marginBottom: SPACE.sm },
  card: { flexDirection: 'row', backgroundColor: 'rgba(26,18,38,0.8)', borderRadius: RADIUS.sm, padding: SPACE.md, gap: SPACE.sm },
  cardContent: { flex: 1 },
  cardTitle: { color: '#E8E0F0', fontSize: 14, fontWeight: '600', marginBottom: 4 },
  cardBody: { color: '#6B5B8A', fontSize: 12, lineHeight: 18 },
  rightsText: { color: '#10B981', fontSize: 12, textAlign: 'center', marginTop: SPACE.sm },
  aiCard: { flexDirection: 'row', backgroundColor: 'rgba(245,158,11,0.08)', borderRadius: RADIUS.sm, padding: SPACE.md, gap: SPACE.sm, marginBottom: SPACE.lg, alignItems: 'flex-start' },
  aiText: { color: '#F59E0B', fontSize: 12, flex: 1, lineHeight: 18 },
  contactBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: SPACE.sm, paddingVertical: SPACE.md },
  contactText: { color: '#A855F7', fontSize: 13 },
  copyright: { color: '#6B5B8A', fontSize: 11, textAlign: 'center', marginTop: SPACE.sm, paddingBottom: SPACE.xl },
});
